-- Fila separada para pesquisar manualmente no Instagram sem alterar `leds`.
create table if not exists public.instagram_buscas (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    atualizado_em timestamptz not null default now(),
    lead_origem_id bigint not null references public.leds(id),
    nome_pesquisado text not null,
    consulta text not null,
    instagram_search_url text not null,
    status text not null default 'pendente'
        check (status in ('pendente', 'em_pesquisa', 'resultados_salvos', 'sem_resultado', 'descartada')),
    observacao text,
    unique (lead_origem_id)
);

create index if not exists instagram_buscas_status_id_idx
    on public.instagram_buscas (status, id);

alter table public.instagram_buscas enable row level security;
